version: '3'

services:
  ecommerce:
    container_name: ecommerce
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env_example
    depends_on:
      - ecommerce-db
      - ecommerce-redis
    command:
      - ./start-django.sh
    ports:
      - "8000:8000"

  ecommerce-db:
    container_name: ecommerce-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: qwerty123
    ports:
      - "6543:5432"

  ecommerce-redis:
    container_name: ecommerce-redis
    image: redis:7
    ports:
      - "6738:6739"
